version: "3.9"
services:
  postgresql-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"